include: package:surf_lint_rules/analysis_options.yaml

analyzer:
  errors:
    implicit_dynamic_type: false
    implicit_dynamic_parameter: false
    implicit_dynamic_map_literal: false
    implicit_dynamic_function: false
    implicit_dynamic_variable: false
    implicit_dynamic_method: false
    implicit_dynamic_list_literal: false
    implicit_dynamic_invoke: false
    avoid_dynamic_calls: false
    use_build_context_synchronously: false
    avoid_print: false
    close_sinks: false
    return_of_invalid_type: false
    non_bool_condition: false
    todo: ignore


  exclude:
    - "build/**"
    - "script/**"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "docs/templates/**"
    - "plugins/**/**"

dart_code_metrics:
  anti-patterns:
    long-method: false
    long-parameter-list: false
  metrics-exclude:
    - test/**
  rules:
    avoid-unnecessary-setstate: true
    no-boolean-literal-compare: true
    prefer-intl-name: true
    provide-correct-intl-args: true
    avoid-wrapping-in-padding: true
    double-literal-format: true
    binary-expression-operand-order: true
    prefer-single-widget-per-file:
      ignore-private-widgets: true
    no-empty-block: false
    always-remove-listener: true
    avoid-unused-parameters: true
    newline-before-return: false
    prefer-trailing-comma: false
    prefer-conditional-expressions: false

linter:
  rules:
    omit_local_variable_types: false
    always_use_package_imports: false # do not delete
    parameter_assignments: false
    unawaited_futures: false
    avoid_returning_null: false
    avoid_implementing_value_types: false
    use_setters_to_change_properties: false
    only_throw_errors: false
