name: dart_lang_learning
description: A simple command-line application.

environment:
  sdk: '>=2.17.0 <3.0.0'

dev_dependencies:
  surf_lint_rules: ^1.5.0

dependencies:
  http: ^0.13.4
  translator: ^0.1.7
  rxdart: ^0.27.4